class Bangalore
{
	public static void main(String[] args)
	{
		String area="all areas are full of vehicles";
		System.out.println("area:"+area);
		String mainroad="it has heavy traffic in evenings";
		System.out.println("mainroad:"+mainroad);
		String shops="every road has min 10 shops";
		System.out.println("shops:"+shops);
		String house="every house has min 2 floors";
		System.out.println("house:"+house);
		String people="all people in bangalore used to go for work";
		System.out.println("people:"+people);
		String ladies="woman wants to work independently";
		System.out.println("ladies:"+ladies);
		String work="every man wished to work multitask";
		System.out.println("work:"+work);
		String balance="every woman balancing both office and home works";
		System.out.println("balance:"+balance);
		String doors="all home doors are beautifully designed";
		System.out.println("doors:"+doors);
		String phone="every person used to work with an android";
		System.out.println("phone:"+phone);
		String flower="flowe market have high demand";
		System.out.println("flower:"+flower);
		String fruits="fruits are costly nowadays";
		System.out.println("fruits:"+fruits);
		String vegetables="the prices of vegetables are vary day by day";
		System.out.println("vegetables:"+vegetables);
		String market="every city has a market";
		System.out.println("market:"+market);
		String temple="each street has min 3 temples";
		System.out.println("temple:"+temple);
		String weather="weather has keep changing in bangalore";
		System.out.println("weather:"+weather);
		String rain="it has been raining weekly once";
		System.out.println("rain:"+rain);
		String bmtcbus="buses can travel in a small roads";
		System.out.println("bmtcbus:"+bmtcbus);
		String hotel="the people loves to go to hotel";
		System.out.println("hotel:"+hotel);
		String bar="every man visit a bar";
		System.out.println("bar:"+bar);
		String retaurant="these inn became famous in trying new dishes";
		System.out.println("retaurant:"+retaurant);
		String college="every year student's joining rate is increasing";
		System.out.println("college:"+college);
		String students="students loved to go for chats after the class";
		System.out.println("students:"+students);
		String chatpoint="these stalls became attractive for all";
		System.out.println("chatpoint:"+chatpoint);
		String snacks="i want any snacks for every evening";
		System.out.println("snacks:"+snacks);
		String gobistalls="its there in every street";
		System.out.println("gobistalls:"+gobistalls);
		String panipuri="its price reached peak nowadays";
		System.out.println("panipuri:"+panipuri);
		String vans="every school has min 5 to 6 vans";
		System.out.println("vans:"+vans);
		String clgVan="even clg also have 6 to 7 buses";
		System.out.println("clgVan:"+clgVan);
		String parking="max 500 bikes are parked in every college";
		System.out.println("parking:"+parking);
		String mantapa="its used to gathering a people to discuss something";
		System.out.println("mantapa:"+mantapa);
		String conventionHall="these halls became luxurious";
		System.out.println("conventionHall:"+conventionHall);
		String events="the owner of event management getting high income";
		System.out.println("events:"+events);
		String musicSys="every building has musicSystem";
		System.out.println("musicSys:"+musicSys);
		String glossery="we bring glosseries every 2 months";
		System.out.println("glossery:"+glossery);
		String ration="rural people get their ration from government system";
		System.out.println("ration:"+ration);
		String trees="we have to plant more trees";
		System.out.println("trees:"+trees);
		String children="they uses bus to travel for their schools";
		System.out.println("children:"+children);
		String traffic="every circle has a huge traffic";
		System.out.println("traffic:"+traffic);
		String signals="its the very useful for us to avoid accidents";
		System.out.println("signals:"+signals);
		String animals="pets are very carable in this city";
		System.out.println("animals:"+animals);
		String pets="they also costs till lakhs";
		System.out.println("pets:"+pets);
		String pg="students used to stay in pg's for their needs";
		System.out.println("pg:"+pg);
		String railways="people used trains to travel";
		System.out.println("railways:"+railways);
		String flights="people used flights to travel far in less time";
		System.out.println("flights:"+flights);
		String airport="all aeroplanes are landed in airport";
		System.out.println("airport:"+airport);
		String taxi="people used taxi to reach their exact location";
		System.out.println("taxi:"+taxi);
		String shopping="in bangalore, there are multiple shopping centers are there";
		System.out.println("shopping:"+shopping);
		String collections="every month has new collections in everything";
		System.out.println("collections:"+collections);
		String dishes="the vlogers tried new dishes to attract people";
		System.out.println("dishes:"+dishes);
		String watersupply="every house has water connection";
		System.out.println("watersupply:"+watersupply);
		String sunlight="its also useful and harmful to skin";
		System.out.println("sunlight:"+sunlight);
		String moon="it is very attractive during fullmoon days";
		System.out.println("moon:"+moon);
		String automobiles="they have tiny materials to sell";
		System.out.println("automobiles:"+automobiles);
		String textiles="these shops have huge collections for festivals";
		System.out.println("textiles:"+textiles);
		String festivals="people celebrate every festivals";
		System.out.println("festivals:"+festivals);
		String songs="people used to litsen songs in all languages";
		System.out.println("songs:"+songs);
		String shows="people entertained by reality shows on weekends";
		System.out.println("shows:"+shows);
		String crackers="people burn the crackers in diwali";
		System.out.println("crackers:"+crackers);
		String tiles="its has different styles and designs";
		System.out.println("tiles:"+tiles);
		String cups="cups are numerously designed";
		System.out.println("cups:"+cups);
		String sandals="both men and women has various collections";
		System.out.println("sandals:"+sandals);
		String art="art includes painting, designing, creative things";
		System.out.println("art:"+art);
		String frame="photo frame looks attractive on the wall";
		System.out.println("frame:"+frame);
		String shoes="white pair of shoes looks mass";
		System.out.println("shoes:"+shoes);
		String rice="there are different types of rice are available";
		System.out.println("rice:"+rice);
		String medals="I collected 49 medals till now";
		System.out.println("medals:"+medals);
		String clothes="I used to wash clothes twicw a day";
		System.out.println("clothes:"+clothes);
		String cottonbags="these are used to avoid plastic";
		System.out.println("cottonbags:"+cottonbags);
		String sports="sports is a good physical activity to maintain health";
		System.out.println("sports:"+sports);
		String movies="a new movie releases on every friday";
		System.out.println("movies:"+movies);
		String medicines="medicines are cheaply avilable in modi medicals";
		System.out.println("medicines:"+medicines);
		String trophy="a real happiness in receiving trophies";
		System.out.println("trophy:"+trophy);
		String certificate="we have to maintain certificates for references";
		System.out.println("certificate:"+certificate);
		String night="cities are looks heaven at nights";
		System.out.println("night:"+night);
		String record="hospitals has maintained a records of patients";
		System.out.println("record:"+record);
		String plates="glass plates are used carefully";
		System.out.println("area:"+area);
			
	}
}  