class City
{
	public static void main(String[] args)
	{
		String marriage="marriage is the biggest dream in everyones's life";
		System.out.println("marriage:"+marriage);
		String marriageDay=marriage+", also it becoming true";
		System.out.println("marriageDay:"+marriageDay);
		String trip="we are planning to go to andrapradesh";
		System.out.println("trip:"+trip);
		String day1=" with our family and neighbours";
		System.out.println("day1:"+day1);
		String result=trip+day1;
		System.out.println("result:"+result);
		String town="we went to hometown monthly once";
		System.out.println("town:"+town);
		String village=town+" with my friends";
		System.out.println("village:"+village);
		String news="they provide useful information";
		System.out.println("news:"+news);
		String people=" that helps people to live with surroundings";
		System.out.println("people:"+people);
		String channel=news+people;
		System.out.println("channel:"+channel);
		String time="people has to manage time";
		System.out.println("time:"+time);
		String management="to complete their tasks at a given time";
		System.out.println("management:"+management);
		String completing="time+management";
		System.out.println("completing:"+completing);
		String job="we learn some skills to get a good job";
		System.out.println("job:"+job);
		String also=" also learn to represent the thing we know";
		System.out.println("also:"+also);
		String aim="job+also";
		System.out.println("aim:"+aim);
		String desk="desks are made by woood";
		System.out.println("desk:"+desk);
		String bench=desk+" also they got polished";
		System.out.println("bench:"+bench);
		String states="there are 30 states in our country";
		System.out.println("states:"+states);
		String capital=" with their capitals";
		System.out.println("capital:"+capital);
		String India="states+capital";
		System.out.println("India:"+India);
		String charge="electrical vehicles are becoming highly demand";
		System.out.println("charge:"+charge);
		String electric="bikes, cars, and other vehicles are available in electric mode";
		System.out.println("electric:"+electric);
		String current="charge+electric";
		System.out.println("current:"+current);
		String laptop="it has central processing unit";
		System.out.println("laptop:"+laptop);
		String storage=" also it has storage space";
		System.out.println("storage:"+storage);
		String computer="laptop+storage";
		System.out.println("computer:"+computer);
		String monitor="connects user interface with cpu";
		System.out.println("monitor:"+monitor);
		String cpu="it intermediate to the storage database";
		System.out.println("cpu:"+cpu);
		String process="this process is called building an application";
		System.out.println("process:"+process);
		String web=monitor+cpu+process;
		System.out.println("web:"+web);
		String processingunit="it has two java tecnologies";
		System.out.println("processingunit:"+processingunit);
		String toBuild="there are servlet and JDBC";
		System.out.println("toBuild:"+toBuild);
		String types="in that spring and JPA are sub technologies";
		System.out.println("types:"+types);
		String technologies="these intermediate with SQL web technology";
		System.out.println("technologies:"+technologies);
		String buildingProcess="types"+"technologies";
		System.out.println("buildingProcess:"+buildingProcess);
		String userInterface="html, css, js, bootsrap and ajax";
		System.out.println("userInterface:"+userInterface);
		String start="these are the 5 techniques used in UI";
		System.out.println("start:"+start);
		String stop="database consists of SQL web technology";
		System.out.println("stop:"+stop);
		String labs="labs have multiple computers to operate";
		System.out.println("labs:"+labs);
		String connection="all computers get connected with network";
		System.out.println("connection:"+connection);
		String wire="they have even wireless connections also";
		System.out.println("wire:"+wire);
		String wirelessdata=start+stop+labs;
		System.out.println("wirelessdata:"+wirelessdata);
		String unitdata=buildingProcess+userInterface;
		System.out.println("unitdata:"+unitdata);
		String keys="there are 102 buttons in the keyboard";
		System.out.println("keys:"+keys);
		String buttons=keys+" also they have multiple fuctions in each buttons";
		System.out.println("buttons:"+buttons);
		String shortcut="there can be shortcut keys are there to use";
		System.out.println("shortcut:"+shortcut);
		String battery="some batteries are used to maintain computers";
		System.out.println("battery:"+battery);
		String uses=shortcut+battery;
		System.out.println("uses:"+uses);
		String numericals="numbers from 0 to 1 has special characters";
		System.out.println("numericals:"+numericals);
		String alphabets="26 alphabets have both uppercase and lowecase";
		System.out.println("alphabets:"+alphabets);
		String operations=numericals+alphabets;
		System.out.println("operations:"+operations);
		String memory="it has data stored in bytecode";
		System.out.println("memory:"+memory);
		String hardDisk="it is used to store data";
		System.out.println("hardDisk:"+hardDisk);
		String compactDisk="it stores media files";
		System.out.println("compactDisk:"+compactDisk);
		String twoDisks=hardDisk+"&"+compactDisk;
		System.out.println("twoDisks:"+twoDisks);
		String thread="java is a multi threading programming language";
		System.out.println("thread:"+thread);
		String newtech="java uses several technologies to build applications";
		System.out.println("newtech:"+newtech);
		String arc="its used to cut the curve";
		System.out.println("arc:"+arc);
		String arch=arc+"architecture";
		System.out.println("arch:"+arch);
		String someData="some data can be hide from the developer";
		System.out.println("someData:"+someData);
		String chair="they have different collections";
		System.out.println("chair:"+chair);
		String sofaSet="they can range from thousands to lakhs together";
		System.out.println("sofaSet:"+sofaSet);
		String furniture=chair+sofaSet;
		System.out.println("furniture:"+furniture);
		String stationary="it includes all the stationaries";
		System.out.println("stationary:"+stationary);
		String things=" that all needed by students and learners";
		System.out.println("things:"+things);
		String bookStore=stationary+things;
		System.out.println("bookStore:"+bookStore);
		String fancy="this store includes all fancy items";
		System.out.println("fancy:"+fancy);
		String mehendi="mehendi is a beautiful emotion to the girls";
		System.out.println("mehendi:"+mehendi);
		String nails="we put colours to the nails in a different method";
		System.out.println("nails:"+nails);
		String care="people used to take care about their skin";
		System.out.println("care:"+care);
		String chocolate="people who loves chocolate are so sweet";
		System.out.println("chocolate:"+chocolate);
		String oneLove=" like me";
		System.out.println("oneLove:"+oneLove);
		String meAs=chocolate+oneLove;
		System.out.println("meAs:"+meAs);
		String alsoMe="always loved to eat bakery items";
		System.out.println("alsoMe:"+alsoMe);
		String foodie=alsoMe+" with my brother and sister";
		System.out.println("foodie:"+foodie);
	}
}